name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  build:
    name: "Build and Run tests"
    strategy:
      fail-fast: false
      matrix:
        info:
          - os: "macos-latest"
            target: "x86_64-apple-darwin"
          - os: "macos-latest"
            target: "aarch64-apple-darwin"
    runs-on: ${{ matrix.info.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: ${{ matrix.info.target }}

      - name: Enable Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: false

      - name: Fmt Check
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy

      - name: Download test files
        run: cd tests && wget -O ./test_data.zip https://github.com/mandiant/macos-UnifiedLogs/releases/download/v1.0.0/test_data.zip && unzip test_data.zip

      - name: Build tests
        run: cargo test --no-run --release

      - name: Run tests
        run: cargo test --release
